/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conmutacion;

import basicgraph.Graph;
import basicgraph.Vertex;
import com.jcraft.jsch.JSchException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author RICHARD
 */
public class Interfaz extends javax.swing.JFrame {
    private static final String USERNAME = "administrador";
    private static final int PORT = 22;
    private static final String PASSWORD = "administrador";
    Graph relacion;
    /**
     * Creates new form Interfaz1
     */
    public Interfaz() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        crearVrf = new javax.swing.JRadioButton();
        cliente = new javax.swing.JComboBox<>();
        ciudad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vlan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        eliminarVrf = new javax.swing.JRadioButton();
        cliente1 = new javax.swing.JComboBox<>();
        ciudad1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        vlan1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        conectividad = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        origen = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        destino = new javax.swing.JList<>();
        ejecutar = new javax.swing.JButton();
        red = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        texto1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Proyecto de Conmutación y Enrutamiento ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("MPLS VPN L3");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        crearVrf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        crearVrf.setText("Crear VRF");
        crearVrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVrfActionPerformed(evt);
            }
        });

        cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NESTLE", "HONESA", " " }));

        ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUAYAQUIL", "QUITO" }));
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre cliente ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Vlan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ciudad");

        vlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearVrf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ciudad, 0, 96, Short.MAX_VALUE)
                    .addComponent(vlan))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearVrf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        eliminarVrf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eliminarVrf.setText("Eliminar Vrf");
        eliminarVrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVrfActionPerformed(evt);
            }
        });

        cliente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NESTLE", "HONESA" }));
        cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente1ActionPerformed(evt);
            }
        });

        ciudad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUAYAQUIL", "QUITO" }));
        ciudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudad1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nombre cliente ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Vlan");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Ciudad");

        vlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eliminarVrf))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cliente1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ciudad1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vlan1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarVrf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        conectividad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conectividad.setText("Conectividad");
        conectividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectividadActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Origen");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Destino");

        origen.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        origen.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CE-GYE-NESTLE", "CE-GYE-HONESA", "CE-UIO-NESTLE", "CE-UIO-HONESA", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(origen);

        destino.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        destino.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CE-GYE-NESTLE", "CE-GYE-HONESA", "CE-UIO-NESTLE", "CE-UIO-HONESA", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(destino);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(conectividad)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(conectividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ejecutar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        red.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        red.setText("Observar Red");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(texto1);

        texto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane5.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(263, 263, 263))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(161, 161, 161))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(ejecutar)
                                .addGap(38, 38, 38)
                                .addComponent(red))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ejecutar)
                            .addComponent(red))
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Habilitamos todos los parametros para crear Vrf y desabilitamos el resto
    private void crearVrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVrfActionPerformed
        vlan.setEnabled(true);
        cliente.setEnabled(true);
        ciudad.setEnabled(true);
        texto1.setEnabled(false);
        vlan1.setEnabled(false);
        cliente1.setEnabled(false);
        ciudad1.setEnabled(false);
        origen.setEnabled(false);
        destino.setEnabled(false);
       eliminarVrf.setSelected(false);
       conectividad.setSelected(false);

    }//GEN-LAST:event_crearVrfActionPerformed

//Habilitamos todos los parametros para eliminar Vrf y desabilitamos el resto
    private void eliminarVrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVrfActionPerformed
        vlan1.setEnabled(true);
        cliente1.setEnabled(true);
        ciudad1.setEnabled(true);
        texto1.setEnabled(false);
        vlan.setEnabled(false);
        cliente.setEnabled(false);
        ciudad.setEnabled(false);
        origen.setEnabled(false);
        destino.setEnabled(false);
        crearVrf.setSelected(false);
        conectividad.setSelected(false);
    }//GEN-LAST:event_eliminarVrfActionPerformed

    private void cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente1ActionPerformed

    private void ciudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudad1ActionPerformed

    //Habilitamos todos los parametros para hacer ping entre dos clientes y desabilitamos el resto
    private void conectividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectividadActionPerformed
        
        vlan.setEnabled(false);
        cliente.setEnabled(false);
        ciudad.setEnabled(false);
        vlan1.setEnabled(false);
        cliente1.setEnabled(false);
        ciudad1.setEnabled(false);
        origen.setEnabled(true);
        destino.setEnabled(true);
        crearVrf.setSelected(false);
        eliminarVrf.setSelected(false);
       
    }//GEN-LAST:event_conectividadActionPerformed
        //Realiza la operacion de la opcion elegida 
    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        //Crear Vrf
        if(crearVrf.isSelected()){
            CrearVrf();
        }else if(eliminarVrf.isSelected()){
          EliminarVrf();
        //Conectividad
        }else if(conectividad.isSelected()){
            String ip = "",ip1="";
            String origen=this.origen.getSelectedValue();
            String destino=this.destino.getSelectedValue();
            ip=ip(origen);
            System.out.println(ip);
            ip1=ip(destino);
            System.out.println(ip1);
            try {
                SSHConnector sshConnector = new SSHConnector();
                
                sshConnector.connect(USERNAME, PASSWORD, ip, PORT);
           
                String result = sshConnector.executeCommand(ip1,3,null);
                texto1.setText(result);
                sshConnector.disconnect();
                System.out.println(result);
            } catch (JSchException ex) {
                System.out.println("No se pudo ejecutar los comandos");
            } catch (IllegalAccessException ex) {
                System.out.println("No se pudo conectar");
            } catch (IOException ex) {
                System.out.println("Error de comando ingresado");
            } catch (InterruptedException ex) {
                System.out.println("La sesion fue interrumpida");
            }

        }
    }//GEN-LAST:event_ejecutarActionPerformed
    private String ip(String origen){
          String ip = "";
            if(origen=="CE-GYE-NESTLE"){
                ip="192.168.1.10";
            }else if(origen=="CE-UIO-NESTLE"){
                ip="10.20.10.2";
            }else if(origen=="CE-GYE-HONESA"){
                ip="10.10.10.6";
            }else if(origen=="CE-UIO-HONESA"){
                ip="10.20.10.6";
            } 
        return ip;    
    }
    private void CrearVrf(){
        texto.setText("");
        String tex="Se creara la VRF en la VLAN  ";
        tex=tex+vlan.getText();
        tex=tex+" al cliente "+(String) cliente.getSelectedItem()+" en la ciudad de "+ (String) ciudad.getSelectedItem();
        if(vlan.getText().isEmpty()){
           texto.setText("Error: Ingrese todos los parametros "); 
        }else {
           try {
             int vlan1=Integer.parseInt(vlan.getText());
             int acum=0;
             String text="";
                LeerVrf vrf=new LeerVrf();
                LinkedList<CE> listaVrf=vrf.cargarVrf();
             for (CE obj : listaVrf) {
                 acum=acum+1;
                 System.out.println(obj);
                 //validaciones 
                 boolean igualCiudad=ciudad.getSelectedItem().equals(obj.ciudad);
                 boolean igualCliente=cliente.getSelectedItem().equals(obj.cliente);
                 boolean igualVlan=vlan1==obj.vlan;
                
                if(igualCiudad && igualCliente ){
                    
                    texto.setText(texto.getText()+"En la ciudad "+ obj.ciudad+ " ya existe vrf para el cliente  "+ obj.cliente); 
                } else  {
                    if(igualCiudad && igualVlan ){
                        texto.setText(texto.getText()+"En la ciudad "+ obj.ciudad+ "ya existe la Vlan"+ obj.vlan);  
                    }else{
                       if(acum==listaVrf.size()){
                           if (texto.getText().isEmpty()){
                               CE crear=new CE();
                               crear.setCiudad((String) ciudad.getSelectedItem());
                               crear.setCliente((String) cliente.getSelectedItem());
                               crear.setVlan(vlan1);
                               texto.setText(texto.getText()+"Se Creara con exito la Vrf en la "+ ciudad.getSelectedItem()+ " para el cliente "+ cliente.getSelectedItem() +" la Vlan " +vlan1); 
                               vrf.guardarVrf(listaVrf,crear,"crear"); 
                               EditarVrf(crear,1);
                           }
                        }
                    }  
                }

             }
            } catch (NumberFormatException nfe){
                texto.setText("Error: Ingrese una correcta Vlan ");
            }    
        }
    }
    
 private void EditarVrf(CE obj, int operacion){
       String ip = "",ip1="";
        String origen=ipPe(obj.ciudad);
        System.out.println(origen);
        SSHConnector sshConnector = new SSHConnector(); //Eliminar Vrf
        try {
            sshConnector.connect(USERNAME, PASSWORD, origen, PORT);
             String result = sshConnector.executeCommand(ip1,operacion,obj);
              texto1.setText(result);
            sshConnector.disconnect();
            System.out.println(result);
         } catch (JSchException ex) {
            System.out.println("No se pudo ejecutar los comandos");
        } catch (IllegalAccessException ex) {
            System.out.println("No se pudo conectar");
        } catch (IOException ex) {
            System.out.println("Error de comando ingresado");
        } catch (InterruptedException ex) {
            System.out.println("La sesion fue interrumpida");
        }
           
    }   
    
    
 private String ipPe(String ciudad){
          String ip = "";
            if(ciudad.equals("GUAYAQUIL")){
                ip="192.168.1.10";
            }else {
                ip="10.20.10.1";
            }
        return ip;    
    }
    
    
    
   private void EliminarVrf(){
       
        String tex="Se Eliminara la VRF en la VLAN  ";
        tex=tex+vlan1.getText();
        tex=tex+" al cliente "+(String) cliente1.getSelectedItem()+" en la ciudad de "+ (String) ciudad1.getSelectedItem();
        if(vlan1.getText().isEmpty()){
           texto.setText("Error: Ingrese todos los parametros "); 
        }else {
           try {
                texto.setText("");
             int vlan=Integer.parseInt(vlan1.getText());
             int acum=0;
              LeerVrf vrf=new LeerVrf();
              LinkedList<CE> listaVrf=vrf.cargarVrf();
              
             for (CE obj : listaVrf) {
                 acum=acum+1;
                 System.out.println(obj);
                 System.out.println("");
                 //validaciones 
                 boolean igualCiudad=ciudad1.getSelectedItem().equals(obj.ciudad);
                 boolean igualCliente=cliente1.getSelectedItem().equals(obj.cliente);
                 boolean igualVlan=vlan==obj.vlan;

                if(igualCiudad && igualCliente && igualVlan ){
                    texto.setText(texto.getText()+"Se eliminara con exito la Vrf en la de "+ obj.ciudad+ " para el cliente "+ obj.cliente +" la Vlan " +obj.vlan); 
                    vrf.guardarVrf(listaVrf,obj,"eliminar");
                    EditarVrf(obj,2);
                  
                } else  {
                   if(acum==listaVrf.size()){
                       if (texto.getText().isEmpty()){
                           texto.setText("No existe la Vrf para ese cliente"); 
                       }
                   }
                }

             }
             acum=0;
            } catch (NumberFormatException nfe){
                texto.setText("Error: Ingrese una correcta Vlan ");
            }    
    }

    }
    private void vlan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlan1ActionPerformed

    private void vlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlanActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        Graph mpls = new Graph(Graph.Type.DIRECTED) {};
        LeerVrf vrf=new LeerVrf();
        LinkedList<CE> listaCE=vrf.cargarVrf();
        //crear objetos 
        CE r1 = new CE();
        Provedor p = new Provedor();
        PE p1 = new PE();
        PE p2 = new PE();
        SW sw = new SW();
        SW sw1 = new SW();
        sw.setCiudad("QUITO");
        sw1.setCiudad("GUAYAQUIL");
        p1.setCiudad("QUITO");
        p2.setCiudad("GUAYAQUIL");
        //crear Vertices de la red
        Vertex isp = new Vertex(p);
        Vertex pe1 = new Vertex(p1);
        Vertex pe2 = new Vertex(p2);
        Vertex swv1 = new Vertex(sw);
        Vertex swv2 = new Vertex(sw1);
        //agregar Vertices a la red
        mpls.addVertex(isp);
        mpls.addVertex(pe1);
        mpls.addVertex(pe2);
        mpls.addVertex(swv1);
        mpls.addVertex(swv2);
        //adyacencias
        mpls.addEdge(isp, pe1);
        mpls.addEdge(isp, pe2);
        mpls.addEdge(pe1, swv1);
        mpls.addEdge(pe2, swv2);
        DefaultListModel modelo = new DefaultListModel();

        Iterator<CE> iterado =  listaCE.iterator();
        while(iterado.hasNext()){
              CE x = iterado.next();
              Vertex ve = new Vertex(x);
              mpls.addVertex(ve);
              if(x.ciudad.equals("QUITO")){
                  mpls.addEdge(swv1, ve);
              }else{
                  mpls.addEdge(swv2, ve);
              }
              
              modelo.addElement(x.getCiudad());
          
       }
      
        try {
            mpls.saveToHtml("Grafo.html", "Grafo de Relacion");
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_redActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ciudad;
    private javax.swing.JComboBox<String> ciudad1;
    private javax.swing.JComboBox<String> cliente;
    private javax.swing.JComboBox<String> cliente1;
    private javax.swing.JRadioButton conectividad;
    private javax.swing.JRadioButton crearVrf;
    private javax.swing.JList<String> destino;
    private javax.swing.JButton ejecutar;
    private javax.swing.JRadioButton eliminarVrf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> origen;
    private javax.swing.JButton red;
    private javax.swing.JTextPane texto;
    private javax.swing.JTextPane texto1;
    private javax.swing.JTextField vlan;
    private javax.swing.JTextField vlan1;
    // End of variables declaration//GEN-END:variables
}
